name = "voice-grocery-app"
compatibility_date = "2024-01-15"
workers_dev = true

main = "./dist/index.html"

[build]
command = "npm run build"

[site]
bucket = "./dist"

[env.production]
name = "voice-grocery-app-production"
VITE_API_URL = "https://example-voice-llm-agent-production.up.railway.app"
