name = "example-llm-voice-agent"
compatibility_date = "2024-01-15"

[build]
command = "npm run build"

[site]
bucket = "./dist"

[env.production]
name = "example-llm-voice-agent-production"
VITE_API_URL = "https://example-voice-llm-agent-production.up.railway.app"
