name = "voice-grocery-app"
compatibility_date = "2024-01-15"

[env.production]
# Production environment variables
# Uncomment and set your production API URL:
# VITE_API_URL = "https://your-backend-api.com"

[build]
command = "npm run build"
publish = "dist"
