name = "voice-grocery-app"
compatibility_date = "2024-01-15"

[env.production]
# Production environment variables
VITE_API_URL = "https://example-voice-llm-agent-production.up.railway.app"

[build]
command = "cd client && npm run build"

[site]
bucket = "client/dist"

[assets]
directory = "client/dist"
