[build]
builder = "nixpacks"
buildMemoryLimit = "4G"

[deploy]
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "on_failure"

[environments.production]
variables = { NODE_ENV = "production" }
